version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    environment:
      - KMAD_WEB_SETTINGS=/usr/src/app/prd_settings.py
    command: gunicorn -k gevent -b 0.0.0.0:8030 kmad_web.application:app
    depends_on:
      - redis
    ports:
      - "8030:8030"
  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    environment:
      - KMAD_WEB_SETTINGS=/usr/src/app/prd_settings.py
    command: celery -A kmad_web.application:celery worker -B -n kmad_web.%h
    volumes:
      - "/Users/langej10/data/kmad:/data"
    depends_on:
      - rabbitmq
      - redis
        # databanks:
        #   build:
        #     context: .
        #     dockerfile: Dockerfile-databanks
        #   command: bash /usr/src/app/schedule_updates.bash
        #   volumes:
        #     - "/srv/kmad:/data"
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq
