version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    depends_on:
      - redis
    ports:
      - "5000:5000"
  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    depends_on:
      - rabbitmq
      - redis
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq
