FROM python:2.7-onbuild

RUN apt-get install -y curl
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash

RUN . ~/.nvm/nvm.sh ; nvm install v4.4.0 ; npm install -g bower ; bower install --allow-root

WORKDIR /usr/src/app
EXPOSE 5000

ENV KMAD_WEB_SETTINGS='/usr/src/app/dev_settings.py'

CMD ["gunicorn", "-k", "gevent", "-b", "0.0.0.0:5000", "kmad_web.application:app"]
