version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    volumes:
      - ".:/usr/src/app"
    command: watchmedo auto-restart -d /usr/src/app -p "*.py" -D -R -- gunicorn -k gevent -b 0.0.0.0:8030 kmad_web.application:app
    environment:
      - KMAD_WEB_SETTINGS=/usr/src/app/dev_settings.py
    depends_on:
      - redis
    ports:
      - "8030:8030"

  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    volumes:
      - ".:/usr/src/app"
      - "/srv/kmad:/data"
    command: watchmedo auto-restart -d /usr/src/app -p "*.py" -D -R -- celery -A kmad_web.application:celery worker -B -n kmad_web.%h
    depends_on:
      - rabbitmq
      - redis
    environment:
      - KMAD_WEB_SETTINGS=/usr/src/app/dev_settings.py

  databanks:
    build:
      context: .
      dockerfile: Dockerfile-databanks
    volumes:
      - ".:/usr/src/app"
      - "/srv/kmad:/data"

  redis:
    image: redis
  rabbitmq:
    image: rabbitmq
